apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment-notification
  namespace: notification

spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app-notification
  template:
    metadata:
      labels:
        app: node-app-notification
    spec:
      containers:
      - name: node-app-notification
        image: CONTAINER_IMAGE
        ports:
        - containerPort: 8080
        env:
        - name: AWS_XRAY_DAEMON_ADDRESS
          value: "10.100.222.158:2000"
---
#k8s services
apiVersion: apps/v1
kind: Service
metadata:
  name: node-app-service-notification
  namespace: notification
spec:
  selector:
    app: node-app-service-notification
  ports:
  - protocol: UDP
    port: 2000
    targetPort: 2000
  type: ClusterIP